server:
  port: 9000
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
feign:
    hystrix:
        enabled: true

ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 1 #(1)
  MaxAutoRetriesNextServer: 1 #(4)
  ReadTimeout: 10000 #(2)
 
             
hystrix:
  command:
 #   "SimpleClient#hello()":
 #     execution:
 #       isolation:
 #         thread:
 #           timeoutInMilliseconds: 5000
    server-2:
      execution:
        isolation:
         thread:
            timeoutInMilliseconds: 5000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
      